import type { Module } from "@/lib/schema";

/**
 * Fundamentals track — the sequential, prerequisite-aware curriculum
 * (PRD §5.6). Each module lists the lessons it contains; flagship lessons are
 * authored in `content/lessons`, the rest render as "in production".
 */
export const MODULES: Module[] = [
  {
    id: "foundations",
    track: "fundamentals",
    order: 1,
    title: "Re-entry & Complexity",
    summary: "How to think about problems, dry runs, and Big-O intuition before any data structure.",
    icon: "gauge",
    difficulty: "intro",
    estMinutes: 45,
    prerequisites: [],
    companyTags: ["Google", "Meta", "Amazon"],
    lessonSlugs: ["complexity-intuition"],
  },
  {
    id: "arrays",
    track: "fundamentals",
    order: 2,
    title: "Arrays & Strings",
    summary: "The memory model, traversal, in-place edits, and frequency counting that unlock everything else.",
    icon: "grid",
    difficulty: "easy",
    estMinutes: 90,
    prerequisites: ["foundations"],
    companyTags: ["Google", "Amazon", "Microsoft", "Meta"],
    lessonSlugs: ["arrays-intro"],
  },
  {
    id: "recursion",
    track: "fundamentals",
    order: 3,
    title: "Recursion & Backtracking",
    summary: "The call stack, base cases, decision trees, and pruning — thinking in smaller subproblems.",
    icon: "git-branch",
    difficulty: "medium",
    estMinutes: 100,
    prerequisites: ["arrays"],
    companyTags: ["Google", "Meta"],
    lessonSlugs: ["recursion-intro"],
  },
  {
    id: "linked-lists",
    track: "fundamentals",
    order: 4,
    title: "Linked Lists",
    summary: "Pointers, reversal, cycle detection, and safe traversal of chained nodes.",
    icon: "list",
    difficulty: "medium",
    estMinutes: 80,
    prerequisites: ["arrays"],
    companyTags: ["Amazon", "Microsoft"],
    lessonSlugs: ["linked-lists-intro"],
  },
  {
    id: "stacks-queues",
    track: "fundamentals",
    order: 5,
    title: "Stacks, Queues & Deques",
    summary: "LIFO/FIFO models, expression handling, monotonic structures, and scheduling.",
    icon: "layers",
    difficulty: "medium",
    estMinutes: 85,
    prerequisites: ["linked-lists"],
    companyTags: ["Amazon", "Google"],
    lessonSlugs: ["stacks-queues-intro"],
  },
  {
    id: "hashing",
    track: "fundamentals",
    order: 6,
    title: "Hashing",
    summary: "Sets, maps, collisions, frequency maps, and the space-for-time tradeoff.",
    icon: "hash",
    difficulty: "medium",
    estMinutes: 70,
    prerequisites: ["arrays"],
    companyTags: ["Meta", "Amazon", "Google"],
    lessonSlugs: ["hashing-intro"],
  },
  {
    id: "sorting",
    track: "fundamentals",
    order: 7,
    title: "Sorting",
    summary: "Comparison sorts, stability, merge & quicksort, and choosing the right sort.",
    icon: "arrow-down-up",
    difficulty: "medium",
    estMinutes: 95,
    prerequisites: ["arrays"],
    companyTags: ["Google", "Microsoft"],
    lessonSlugs: ["sorting-intro"],
  },
  {
    id: "binary-search",
    track: "fundamentals",
    order: 8,
    title: "Binary Search",
    summary: "Search on sorted data, boundaries, and the powerful 'search on the answer' idea.",
    icon: "search",
    difficulty: "medium",
    estMinutes: 75,
    prerequisites: ["sorting"],
    companyTags: ["Google", "Meta", "Amazon"],
    lessonSlugs: ["binary-search-intro"],
  },
  {
    id: "trees",
    track: "fundamentals",
    order: 9,
    title: "Trees & BSTs",
    summary: "Traversals, recursion on trees, height, balance, and BST operations.",
    icon: "tree",
    difficulty: "medium",
    estMinutes: 110,
    prerequisites: ["recursion", "stacks-queues"],
    companyTags: ["Amazon", "Microsoft", "Google"],
    lessonSlugs: ["trees-intro"],
  },
  {
    id: "heaps",
    track: "fundamentals",
    order: 10,
    title: "Heaps & Priority Queues",
    summary: "Heap operations, top-k problems, and streaming data.",
    icon: "triangle",
    difficulty: "hard",
    estMinutes: 80,
    prerequisites: ["trees"],
    companyTags: ["Amazon", "Google"],
    lessonSlugs: ["heaps-intro"],
  },
  {
    id: "graphs",
    track: "fundamentals",
    order: 11,
    title: "Graphs",
    summary: "Representation, BFS, DFS, components, cycles, topological sort, and shortest paths.",
    icon: "share",
    difficulty: "hard",
    estMinutes: 130,
    prerequisites: ["trees", "hashing"],
    companyTags: ["Google", "Meta", "Amazon"],
    lessonSlugs: ["graphs-intro"],
  },
  {
    id: "greedy",
    track: "fundamentals",
    order: 12,
    title: "Greedy Algorithms",
    summary: "Local choices, proof intuition, interval problems, and telling counterexamples.",
    icon: "coins",
    difficulty: "hard",
    estMinutes: 70,
    prerequisites: ["sorting"],
    companyTags: ["Google", "Amazon"],
    lessonSlugs: ["greedy-intro"],
  },
  {
    id: "dp",
    track: "fundamentals",
    order: 13,
    title: "Dynamic Programming",
    summary: "State, transition, memoization, tabulation, and grid problems.",
    icon: "boxes",
    difficulty: "hard",
    estMinutes: 140,
    prerequisites: ["recursion", "greedy"],
    companyTags: ["Google", "Meta", "Amazon", "Microsoft"],
    lessonSlugs: ["dp-intro"],
  },
  {
    id: "cp-toolkit",
    track: "fundamentals",
    order: 14,
    title: "Competitive Programming Toolkit",
    summary: "Node.js fast I/O, bit tricks, prefix techniques, BigInt, and modular arithmetic.",
    icon: "swords",
    difficulty: "hard",
    estMinutes: 100,
    prerequisites: ["dp"],
    companyTags: ["Codeforces"],
    lessonSlugs: ["cp-toolkit-intro"],
  },
  {
    id: "cpp-stl",
    track: "fundamentals",
    order: 15,
    title: "C++ STL for Competitive Programming",
    summary: "vector, sort, set/map, priority_queue, and the ready-made algorithms that win contests.",
    icon: "terminal",
    difficulty: "medium",
    estMinutes: 90,
    prerequisites: ["arrays", "sorting"],
    companyTags: ["Codeforces", "Google"],
    lessonSlugs: ["cpp-stl-intro"],
  },
  {
    id: "advanced",
    track: "fundamentals",
    order: 16,
    title: "Advanced Structures",
    summary: "Disjoint set union, tries, Fenwick trees, and segment trees.",
    icon: "network",
    difficulty: "hard",
    estMinutes: 120,
    prerequisites: ["graphs", "dp"],
    companyTags: ["Google", "Codeforces"],
    lessonSlugs: ["advanced-intro"],
  },
];

export function getModule(id: string) {
  return MODULES.find((m) => m.id === id);
}

export const MODULE_COUNT = MODULES.length;
