import type { PracticeItem } from "@/lib/schema";

/**
 * Pattern bank — a comprehensive, interview-focused problem set organized by
 * pattern and difficulty (curated from NeetCode 150, Blind 75, and the
 * Tech Interview Handbook). Each problem is assigned its single primary pattern
 * so the "By Pattern" view groups cleanly. We store only canonical URLs and
 * spoiler-free hints — never the copyrighted statement.
 *
 * These merge into PRACTICE_ITEMS (deduped by id) alongside the base set.
 */
export const PATTERN_BANK: PracticeItem[] = [
  // ===================== Frequency Counting & Hashing =====================
  { id: "lc-majority-element", title: "Majority Element", platform: "leetcode", url: "https://leetcode.com/problems/majority-element/", difficulty: "easy", topic: "Hashing", pattern: "frequency-hashing", estMinutes: 12, hint: "Boyer-Moore voting: keep a candidate and a running count.", companyTags: ["Amazon", "Adobe"], freshness: "2026-07-01" },
  { id: "lc-ransom-note", title: "Ransom Note", platform: "leetcode", url: "https://leetcode.com/problems/ransom-note/", difficulty: "easy", topic: "Hashing", pattern: "frequency-hashing", estMinutes: 12, hint: "Count letters in the magazine, then spend them on the note.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-valid-sudoku", title: "Valid Sudoku", platform: "leetcode", url: "https://leetcode.com/problems/valid-sudoku/", difficulty: "medium", topic: "Hashing", pattern: "frequency-hashing", estMinutes: 20, hint: "Track seen digits per row, column, and 3×3 box with sets.", companyTags: ["Amazon", "Apple"], freshness: "2026-07-01" },
  { id: "lc-longest-consecutive", title: "Longest Consecutive Sequence", platform: "leetcode", url: "https://leetcode.com/problems/longest-consecutive-sequence/", difficulty: "medium", topic: "Hashing", pattern: "frequency-hashing", estMinutes: 25, hint: "Put all in a set; only start counting at sequence-starters (no x−1).", companyTags: ["Google", "Meta", "Amazon"], freshness: "2026-07-01" },

  // ============================ Two Pointers =============================
  { id: "lc-remove-duplicates-sorted", title: "Remove Duplicates from Sorted Array", platform: "leetcode", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", difficulty: "easy", topic: "Arrays", pattern: "two-pointers", estMinutes: 12, hint: "A slow write-pointer trails the fast read-pointer.", companyTags: ["Microsoft", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-move-zeroes", title: "Move Zeroes", platform: "leetcode", url: "https://leetcode.com/problems/move-zeroes/", difficulty: "easy", topic: "Arrays", pattern: "two-pointers", estMinutes: 12, hint: "Swap non-zeros forward with a write-pointer.", companyTags: ["Meta", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-sort-colors", title: "Sort Colors", platform: "leetcode", url: "https://leetcode.com/problems/sort-colors/", difficulty: "medium", topic: "Arrays", pattern: "two-pointers", estMinutes: 20, hint: "Dutch national flag: low, mid, high pointers in one pass.", companyTags: ["Microsoft", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-trapping-rain-water", title: "Trapping Rain Water", platform: "leetcode", url: "https://leetcode.com/problems/trapping-rain-water/", difficulty: "hard", topic: "Arrays", pattern: "two-pointers", estMinutes: 35, hint: "Two pointers tracking left-max and right-max walls.", companyTags: ["Amazon", "Google", "Goldman Sachs"], freshness: "2026-07-01" },

  // =========================== Sliding Window ============================
  { id: "lc-max-average-subarray", title: "Maximum Average Subarray I", platform: "leetcode", url: "https://leetcode.com/problems/maximum-average-subarray-i/", difficulty: "easy", topic: "Arrays", pattern: "sliding-window", estMinutes: 12, hint: "Fixed-size window sum; slide by adding one, dropping one.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-fruit-into-baskets", title: "Fruit Into Baskets", platform: "leetcode", url: "https://leetcode.com/problems/fruit-into-baskets/", difficulty: "medium", topic: "Arrays", pattern: "sliding-window", estMinutes: 22, hint: "Longest window containing at most two distinct values.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-sliding-window-maximum", title: "Sliding Window Maximum", platform: "leetcode", url: "https://leetcode.com/problems/sliding-window-maximum/", difficulty: "hard", topic: "Arrays", pattern: "sliding-window", estMinutes: 35, hint: "Monotonic decreasing deque of indices; front is the max.", companyTags: ["Amazon", "Google", "Meta"], freshness: "2026-07-01" },

  // ==================== Prefix Sums & Difference Arrays ===================
  { id: "lc-running-sum", title: "Running Sum of 1d Array", platform: "leetcode", url: "https://leetcode.com/problems/running-sum-of-1d-array/", difficulty: "easy", topic: "Arrays", pattern: "prefix-sums", estMinutes: 8, hint: "Each entry adds the previous running total.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-find-pivot-index", title: "Find Pivot Index", platform: "leetcode", url: "https://leetcode.com/problems/find-pivot-index/", difficulty: "easy", topic: "Arrays", pattern: "prefix-sums", estMinutes: 15, hint: "leftSum equals total − leftSum − a[i] at the pivot.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-range-sum-immutable", title: "Range Sum Query — Immutable", platform: "leetcode", url: "https://leetcode.com/problems/range-sum-query-immutable/", difficulty: "easy", topic: "Arrays", pattern: "prefix-sums", estMinutes: 12, hint: "Precompute prefix sums; a range is one subtraction.", companyTags: ["Meta"], freshness: "2026-07-01" },
  { id: "lc-contiguous-array", title: "Contiguous Array", platform: "leetcode", url: "https://leetcode.com/problems/contiguous-array/", difficulty: "medium", topic: "Arrays", pattern: "prefix-sums", estMinutes: 25, hint: "Map running sum (treat 0 as −1) to its first index.", companyTags: ["Meta", "Amazon"], freshness: "2026-07-01" },

  // ========================= Fast & Slow Pointers ========================
  { id: "lc-palindrome-linked-list", title: "Palindrome Linked List", platform: "leetcode", url: "https://leetcode.com/problems/palindrome-linked-list/", difficulty: "easy", topic: "Linked Lists", pattern: "fast-slow-pointers", estMinutes: 18, hint: "Find the middle, reverse the second half, compare.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-linked-list-cycle-ii", title: "Linked List Cycle II", platform: "leetcode", url: "https://leetcode.com/problems/linked-list-cycle-ii/", difficulty: "medium", topic: "Linked Lists", pattern: "fast-slow-pointers", estMinutes: 22, hint: "After they meet, walk one pointer from the head to the entry.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-reorder-list", title: "Reorder List", platform: "leetcode", url: "https://leetcode.com/problems/reorder-list/", difficulty: "medium", topic: "Linked Lists", pattern: "fast-slow-pointers", estMinutes: 25, hint: "Split at the middle, reverse the tail, then weave.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-find-duplicate", title: "Find the Duplicate Number", platform: "leetcode", url: "https://leetcode.com/problems/find-the-duplicate-number/", difficulty: "medium", topic: "Arrays", pattern: "fast-slow-pointers", estMinutes: 25, hint: "Treat values as next-pointers; Floyd's cycle finds the dup.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },

  // =========================== Merge Intervals ===========================
  { id: "lc-interval-intersections", title: "Interval List Intersections", platform: "leetcode", url: "https://leetcode.com/problems/interval-list-intersections/", difficulty: "medium", topic: "Intervals", pattern: "merge-intervals", estMinutes: 22, hint: "Two pointers; overlap is [max(starts), min(ends)].", companyTags: ["Meta", "Google"], freshness: "2026-07-01" },
  { id: "lc-min-arrows-balloons", title: "Minimum Number of Arrows to Burst Balloons", platform: "leetcode", url: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/", difficulty: "medium", topic: "Intervals", pattern: "merge-intervals", estMinutes: 22, hint: "Sort by end; shoot at each end, skipping covered balloons.", companyTags: ["Amazon"], freshness: "2026-07-01" },

  // ===================== Cyclic Placement (Cyclic Sort) ===================
  { id: "lc-missing-number", title: "Missing Number", platform: "leetcode", url: "https://leetcode.com/problems/missing-number/", difficulty: "easy", topic: "Arrays", pattern: "cyclic-placement", estMinutes: 12, hint: "Sum 0..n and subtract the array sum — or XOR everything.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-find-disappeared", title: "Find All Numbers Disappeared in an Array", platform: "leetcode", url: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/", difficulty: "easy", topic: "Arrays", pattern: "cyclic-placement", estMinutes: 18, hint: "Mark index |a[i]|−1 negative; unmarked indices are missing.", companyTags: ["Google"], freshness: "2026-07-01" },
  { id: "lc-set-mismatch", title: "Set Mismatch", platform: "leetcode", url: "https://leetcode.com/problems/set-mismatch/", difficulty: "easy", topic: "Arrays", pattern: "cyclic-placement", estMinutes: 18, hint: "Place each value at its home index; the mismatch reveals both.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-find-all-duplicates", title: "Find All Duplicates in an Array", platform: "leetcode", url: "https://leetcode.com/problems/find-all-duplicates-in-an-array/", difficulty: "medium", topic: "Arrays", pattern: "cyclic-placement", estMinutes: 20, hint: "Negate the slot at |a[i]|−1; a second visit means a duplicate.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-first-missing-positive", title: "First Missing Positive", platform: "leetcode", url: "https://leetcode.com/problems/first-missing-positive/", difficulty: "hard", topic: "Arrays", pattern: "cyclic-placement", estMinutes: 35, hint: "Cyclic-place each value at index value−1, then scan for the gap.", companyTags: ["Amazon", "Google", "Stripe"], freshness: "2026-07-01" },

  // ====================== Binary Search on the Answer =====================
  { id: "lc-search-insert", title: "Search Insert Position", platform: "leetcode", url: "https://leetcode.com/problems/search-insert-position/", difficulty: "easy", topic: "Binary Search", pattern: "binary-search-answer", estMinutes: 12, hint: "Lower-bound: first index whose value is ≥ target.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-first-bad-version", title: "First Bad Version", platform: "leetcode", url: "https://leetcode.com/problems/first-bad-version/", difficulty: "easy", topic: "Binary Search", pattern: "binary-search-answer", estMinutes: 12, hint: "Binary search the boundary where good flips to bad.", companyTags: ["Meta", "Google"], freshness: "2026-07-01" },
  { id: "lc-search-2d-matrix", title: "Search a 2D Matrix", platform: "leetcode", url: "https://leetcode.com/problems/search-a-2d-matrix/", difficulty: "medium", topic: "Binary Search", pattern: "binary-search-answer", estMinutes: 18, hint: "Treat the matrix as one sorted array of length m·n.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-find-peak-element", title: "Find Peak Element", platform: "leetcode", url: "https://leetcode.com/problems/find-peak-element/", difficulty: "medium", topic: "Binary Search", pattern: "binary-search-answer", estMinutes: 20, hint: "Move toward the higher neighbor; a peak must lie that way.", companyTags: ["Google", "Meta"], freshness: "2026-07-01" },
  { id: "lc-capacity-ship-packages", title: "Capacity To Ship Packages Within D Days", platform: "leetcode", url: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", difficulty: "medium", topic: "Binary Search", pattern: "binary-search-answer", estMinutes: 28, hint: "Binary search the capacity; check if it ships in ≤ D days.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-median-two-sorted", title: "Median of Two Sorted Arrays", platform: "leetcode", url: "https://leetcode.com/problems/median-of-two-sorted-arrays/", difficulty: "hard", topic: "Binary Search", pattern: "binary-search-answer", estMinutes: 40, hint: "Binary search the partition of the smaller array.", companyTags: ["Amazon", "Google", "Apple"], freshness: "2026-07-01" },

  // ======================= Monotonic Stack & Queue =======================
  { id: "lc-eval-rpn", title: "Evaluate Reverse Polish Notation", platform: "leetcode", url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/", difficulty: "medium", topic: "Stacks", pattern: "monotonic-stack", estMinutes: 20, hint: "Push numbers; on an operator pop two and push the result.", companyTags: ["Amazon", "LinkedIn"], freshness: "2026-07-01" },
  { id: "lc-next-greater-ii", title: "Next Greater Element II", platform: "leetcode", url: "https://leetcode.com/problems/next-greater-element-ii/", difficulty: "medium", topic: "Stacks", pattern: "monotonic-stack", estMinutes: 22, hint: "Loop the array twice; keep a decreasing stack of indices.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-car-fleet", title: "Car Fleet", platform: "leetcode", url: "https://leetcode.com/problems/car-fleet/", difficulty: "medium", topic: "Stacks", pattern: "monotonic-stack", estMinutes: 25, hint: "Sort by position; a slower car ahead absorbs faster ones.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },

  // ======================== Top-K & Heap Selection =======================
  { id: "lc-last-stone-weight", title: "Last Stone Weight", platform: "leetcode", url: "https://leetcode.com/problems/last-stone-weight/", difficulty: "easy", topic: "Heaps", pattern: "top-k-heap", estMinutes: 15, hint: "Max-heap; smash the two heaviest repeatedly.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-kth-largest-stream", title: "Kth Largest Element in a Stream", platform: "leetcode", url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/", difficulty: "easy", topic: "Heaps", pattern: "top-k-heap", estMinutes: 18, hint: "Keep a size-k min-heap; its root is the answer.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-reorganize-string", title: "Reorganize String", platform: "leetcode", url: "https://leetcode.com/problems/reorganize-string/", difficulty: "medium", topic: "Heaps", pattern: "top-k-heap", estMinutes: 25, hint: "Greedily place the most frequent char, never twice in a row.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-merge-k-lists", title: "Merge k Sorted Lists", platform: "leetcode", url: "https://leetcode.com/problems/merge-k-sorted-lists/", difficulty: "hard", topic: "Heaps", pattern: "top-k-heap", estMinutes: 30, hint: "Min-heap of list heads, or divide-and-conquer pairwise merges.", companyTags: ["Amazon", "Google", "Meta"], freshness: "2026-07-01" },

  // ======================= Tree DFS & BFS Templates ======================
  { id: "lc-same-tree", title: "Same Tree", platform: "leetcode", url: "https://leetcode.com/problems/same-tree/", difficulty: "easy", topic: "Trees", pattern: "tree-traversal", estMinutes: 10, hint: "Compare roots, then recurse on both child pairs.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-balanced-tree", title: "Balanced Binary Tree", platform: "leetcode", url: "https://leetcode.com/problems/balanced-binary-tree/", difficulty: "easy", topic: "Trees", pattern: "tree-traversal", estMinutes: 15, hint: "Return height and a balance flag from one post-order pass.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-subtree-of-another", title: "Subtree of Another Tree", platform: "leetcode", url: "https://leetcode.com/problems/subtree-of-another-tree/", difficulty: "easy", topic: "Trees", pattern: "tree-traversal", estMinutes: 18, hint: "At each node, test sameTree against the target.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-validate-bst", title: "Validate Binary Search Tree", platform: "leetcode", url: "https://leetcode.com/problems/validate-binary-search-tree/", difficulty: "medium", topic: "Trees", pattern: "tree-traversal", estMinutes: 20, hint: "Pass down a valid (low, high) range to each node.", companyTags: ["Amazon", "Meta", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-kth-smallest-bst", title: "Kth Smallest Element in a BST", platform: "leetcode", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", difficulty: "medium", topic: "Trees", pattern: "tree-traversal", estMinutes: 18, hint: "In-order traversal yields sorted order; stop at the k-th.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-right-side-view", title: "Binary Tree Right Side View", platform: "leetcode", url: "https://leetcode.com/problems/binary-tree-right-side-view/", difficulty: "medium", topic: "Trees", pattern: "tree-traversal", estMinutes: 20, hint: "BFS by level; take the last node of each level.", companyTags: ["Meta", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-construct-tree", title: "Construct Binary Tree from Preorder and Inorder", platform: "leetcode", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", difficulty: "medium", topic: "Trees", pattern: "tree-traversal", estMinutes: 28, hint: "Preorder gives the root; inorder splits left/right subtrees.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-max-path-sum", title: "Binary Tree Maximum Path Sum", platform: "leetcode", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", difficulty: "hard", topic: "Trees", pattern: "tree-traversal", estMinutes: 30, hint: "Return best downward path; update a global with left+node+right.", companyTags: ["Amazon", "Meta", "Google"], freshness: "2026-07-01" },
  { id: "lc-serialize-tree", title: "Serialize and Deserialize Binary Tree", platform: "leetcode", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", difficulty: "hard", topic: "Trees", pattern: "tree-traversal", estMinutes: 30, hint: "Pre-order with null markers encodes structure uniquely.", companyTags: ["Amazon", "Meta", "Google"], freshness: "2026-07-01" },

  // ================ Graph Traversal & Component Discovery ================
  { id: "lc-flood-fill", title: "Flood Fill", platform: "leetcode", url: "https://leetcode.com/problems/flood-fill/", difficulty: "easy", topic: "Graphs", pattern: "graph-traversal", estMinutes: 15, hint: "DFS/BFS from the start cell, repainting matching neighbors.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-max-area-island", title: "Max Area of Island", platform: "leetcode", url: "https://leetcode.com/problems/max-area-of-island/", difficulty: "medium", topic: "Graphs", pattern: "graph-traversal", estMinutes: 20, hint: "Flood-fill each island, returning its cell count.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-surrounded-regions", title: "Surrounded Regions", platform: "leetcode", url: "https://leetcode.com/problems/surrounded-regions/", difficulty: "medium", topic: "Graphs", pattern: "graph-traversal", estMinutes: 25, hint: "Mark border-connected regions safe; flip the rest.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-word-ladder", title: "Word Ladder", platform: "leetcode", url: "https://leetcode.com/problems/word-ladder/", difficulty: "hard", topic: "Graphs", pattern: "graph-traversal", estMinutes: 35, hint: "BFS over words differing by one letter; shortest transform.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },

  // ========================= Topological Ordering ========================
  { id: "lc-course-schedule-ii", title: "Course Schedule II", platform: "leetcode", url: "https://leetcode.com/problems/course-schedule-ii/", difficulty: "medium", topic: "Graphs", pattern: "topological-sort", estMinutes: 28, hint: "Kahn's algorithm: repeatedly take zero-indegree nodes.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-min-height-trees", title: "Minimum Height Trees", platform: "leetcode", url: "https://leetcode.com/problems/minimum-height-trees/", difficulty: "medium", topic: "Graphs", pattern: "topological-sort", estMinutes: 30, hint: "Peel leaves layer by layer; the last 1–2 nodes are centers.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-alien-dictionary", title: "Alien Dictionary", platform: "leetcode", url: "https://leetcode.com/problems/alien-dictionary/", difficulty: "hard", topic: "Graphs", pattern: "topological-sort", estMinutes: 35, hint: "Derive letter-order edges from adjacent words, then topo-sort.", companyTags: ["Amazon", "Google", "Meta"], freshness: "2026-07-01" },

  // ====================== Backtracking Decision Trees =====================
  { id: "lc-subsets-ii", title: "Subsets II", platform: "leetcode", url: "https://leetcode.com/problems/subsets-ii/", difficulty: "medium", topic: "Backtracking", pattern: "backtracking", estMinutes: 22, hint: "Sort; skip a duplicate unless it's the first at this depth.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-combination-sum-ii", title: "Combination Sum II", platform: "leetcode", url: "https://leetcode.com/problems/combination-sum-ii/", difficulty: "medium", topic: "Backtracking", pattern: "backtracking", estMinutes: 25, hint: "Each number used once; skip duplicates at the same level.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-palindrome-partitioning", title: "Palindrome Partitioning", platform: "leetcode", url: "https://leetcode.com/problems/palindrome-partitioning/", difficulty: "medium", topic: "Backtracking", pattern: "backtracking", estMinutes: 28, hint: "Cut where the prefix is a palindrome, then recurse on the rest.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-letter-combinations", title: "Letter Combinations of a Phone Number", platform: "leetcode", url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", difficulty: "medium", topic: "Backtracking", pattern: "backtracking", estMinutes: 22, hint: "Recurse digit by digit, appending each mapped letter.", companyTags: ["Amazon", "Meta", "Google"], freshness: "2026-07-01" },
  { id: "lc-generate-parentheses", title: "Generate Parentheses", platform: "leetcode", url: "https://leetcode.com/problems/generate-parentheses/", difficulty: "medium", topic: "Backtracking", pattern: "backtracking", estMinutes: 22, hint: "Add '(' while open < n; add ')' while close < open.", companyTags: ["Amazon", "Google", "Uber"], freshness: "2026-07-01" },
  { id: "lc-n-queens", title: "N-Queens", platform: "leetcode", url: "https://leetcode.com/problems/n-queens/", difficulty: "hard", topic: "Backtracking", pattern: "backtracking", estMinutes: 35, hint: "Place one queen per row; track used columns and diagonals.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-word-search-ii", title: "Word Search II", platform: "leetcode", url: "https://leetcode.com/problems/word-search-ii/", difficulty: "hard", topic: "Backtracking", pattern: "backtracking", estMinutes: 40, hint: "Build a trie of words, then DFS the grid pruning by trie.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },

  // ========================= Greedy Choice Patterns =======================
  { id: "lc-jump-game-ii", title: "Jump Game II", platform: "leetcode", url: "https://leetcode.com/problems/jump-game-ii/", difficulty: "medium", topic: "Greedy", pattern: "greedy-choice", estMinutes: 22, hint: "BFS-like: extend the current jump's reach, count layers.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-partition-labels", title: "Partition Labels", platform: "leetcode", url: "https://leetcode.com/problems/partition-labels/", difficulty: "medium", topic: "Greedy", pattern: "greedy-choice", estMinutes: 22, hint: "Extend each part to the last index of any letter it contains.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-merge-triplets", title: "Merge Triplets to Form Target Triplet", platform: "leetcode", url: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/", difficulty: "medium", topic: "Greedy", pattern: "greedy-choice", estMinutes: 20, hint: "Only use triplets that never exceed the target on any axis.", companyTags: ["Google"], freshness: "2026-07-01" },
  { id: "lc-valid-parenthesis-string", title: "Valid Parenthesis String", platform: "leetcode", url: "https://leetcode.com/problems/valid-parenthesis-string/", difficulty: "medium", topic: "Greedy", pattern: "greedy-choice", estMinutes: 22, hint: "Track the possible range of open brackets as you scan.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },

  // ====================== 1-D Dynamic Programming =========================
  { id: "lc-min-cost-climbing", title: "Min Cost Climbing Stairs", platform: "leetcode", url: "https://leetcode.com/problems/min-cost-climbing-stairs/", difficulty: "easy", topic: "Dynamic Programming", pattern: "one-d-dp", estMinutes: 15, hint: "dp[i] = cost[i] + min(dp[i-1], dp[i-2]).", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-house-robber-ii", title: "House Robber II", platform: "leetcode", url: "https://leetcode.com/problems/house-robber-ii/", difficulty: "medium", topic: "Dynamic Programming", pattern: "one-d-dp", estMinutes: 22, hint: "Houses are circular — rob [0..n-2] or [1..n-1], take the max.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-decode-ways", title: "Decode Ways", platform: "leetcode", url: "https://leetcode.com/problems/decode-ways/", difficulty: "medium", topic: "Dynamic Programming", pattern: "one-d-dp", estMinutes: 25, hint: "dp[i] adds one- and valid two-digit decodings.", companyTags: ["Meta", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-max-product-subarray", title: "Maximum Product Subarray", platform: "leetcode", url: "https://leetcode.com/problems/maximum-product-subarray/", difficulty: "medium", topic: "Dynamic Programming", pattern: "one-d-dp", estMinutes: 25, hint: "Track running max and min — a negative can flip them.", companyTags: ["Amazon", "LinkedIn"], freshness: "2026-07-01" },
  { id: "lc-partition-equal-subset", title: "Partition Equal Subset Sum", platform: "leetcode", url: "https://leetcode.com/problems/partition-equal-subset-sum/", difficulty: "medium", topic: "Dynamic Programming", pattern: "one-d-dp", estMinutes: 28, hint: "Subset-sum to total/2 via a boolean knapsack.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },

  // ================ Grid & Subsequence Dynamic Programming ================
  { id: "lc-min-path-sum", title: "Minimum Path Sum", platform: "leetcode", url: "https://leetcode.com/problems/minimum-path-sum/", difficulty: "medium", topic: "Dynamic Programming", pattern: "grid-dp", estMinutes: 20, hint: "dp[r][c] = grid + min(up, left).", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-unique-paths-ii", title: "Unique Paths II", platform: "leetcode", url: "https://leetcode.com/problems/unique-paths-ii/", difficulty: "medium", topic: "Dynamic Programming", pattern: "grid-dp", estMinutes: 20, hint: "Same grid DP, but obstacles contribute zero paths.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-coin-change-ii", title: "Coin Change II", platform: "leetcode", url: "https://leetcode.com/problems/coin-change-ii/", difficulty: "medium", topic: "Dynamic Programming", pattern: "grid-dp", estMinutes: 25, hint: "Count combinations: iterate coins outside, amounts inside.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-target-sum", title: "Target Sum", platform: "leetcode", url: "https://leetcode.com/problems/target-sum/", difficulty: "medium", topic: "Dynamic Programming", pattern: "grid-dp", estMinutes: 25, hint: "Reduce to a subset-sum on (total + target)/2.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-longest-palindromic-substring", title: "Longest Palindromic Substring", platform: "leetcode", url: "https://leetcode.com/problems/longest-palindromic-substring/", difficulty: "medium", topic: "Dynamic Programming", pattern: "grid-dp", estMinutes: 25, hint: "Expand around each center, or DP over substrings.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-edit-distance", title: "Edit Distance", platform: "leetcode", url: "https://leetcode.com/problems/edit-distance/", difficulty: "hard", topic: "Dynamic Programming", pattern: "grid-dp", estMinutes: 32, hint: "2-D DP over prefixes: insert, delete, or replace.", companyTags: ["Amazon", "Google", "Meta"], freshness: "2026-07-01" },

  // ================== Bitmasking & Subset Enumeration =====================
  { id: "lc-single-number", title: "Single Number", platform: "leetcode", url: "https://leetcode.com/problems/single-number/", difficulty: "easy", topic: "Bit Manipulation", pattern: "bitmasking", estMinutes: 10, hint: "XOR all values; pairs cancel, leaving the unique one.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-number-of-1-bits", title: "Number of 1 Bits", platform: "leetcode", url: "https://leetcode.com/problems/number-of-1-bits/", difficulty: "easy", topic: "Bit Manipulation", pattern: "bitmasking", estMinutes: 10, hint: "n & (n−1) clears the lowest set bit each step.", companyTags: ["Apple", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-counting-bits", title: "Counting Bits", platform: "leetcode", url: "https://leetcode.com/problems/counting-bits/", difficulty: "easy", topic: "Bit Manipulation", pattern: "bitmasking", estMinutes: 15, hint: "bits[i] = bits[i >> 1] + (i & 1).", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-reverse-bits", title: "Reverse Bits", platform: "leetcode", url: "https://leetcode.com/problems/reverse-bits/", difficulty: "easy", topic: "Bit Manipulation", pattern: "bitmasking", estMinutes: 12, hint: "Shift the answer left and pull bits off n one at a time.", companyTags: ["Apple"], freshness: "2026-07-01" },
  { id: "lc-single-number-ii", title: "Single Number II", platform: "leetcode", url: "https://leetcode.com/problems/single-number-ii/", difficulty: "medium", topic: "Bit Manipulation", pattern: "bitmasking", estMinutes: 22, hint: "Count each bit mod 3, or use two-bitmask state machine.", companyTags: ["Google"], freshness: "2026-07-01" },
  { id: "lc-sum-of-two-integers", title: "Sum of Two Integers", platform: "leetcode", url: "https://leetcode.com/problems/sum-of-two-integers/", difficulty: "medium", topic: "Bit Manipulation", pattern: "bitmasking", estMinutes: 22, hint: "XOR sums without carry; (a & b) << 1 is the carry.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },

  // ======================= Union-Find Connectivity ========================
  { id: "lc-redundant-connection", title: "Redundant Connection", platform: "leetcode", url: "https://leetcode.com/problems/redundant-connection/", difficulty: "medium", topic: "Graphs", pattern: "union-find", estMinutes: 25, hint: "Union each edge; the first that connects an already-joined pair is extra.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-accounts-merge", title: "Accounts Merge", platform: "leetcode", url: "https://leetcode.com/problems/accounts-merge/", difficulty: "medium", topic: "Graphs", pattern: "union-find", estMinutes: 30, hint: "Union accounts sharing an email, then group by root.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-most-stones-removed", title: "Most Stones Removed with Same Row or Column", platform: "leetcode", url: "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/", difficulty: "medium", topic: "Graphs", pattern: "union-find", estMinutes: 28, hint: "Union stones sharing a row/column; answer is n − components.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },

  // ================= Mixed-Pattern Recognition & Strategy =================
  { id: "lc-plus-one", title: "Plus One", platform: "leetcode", url: "https://leetcode.com/problems/plus-one/", difficulty: "easy", topic: "Math", pattern: "mixed-recognition", estMinutes: 10, hint: "Carry from the last digit; a leading 9-run needs a new digit.", companyTags: ["Google"], freshness: "2026-07-01" },
  { id: "lc-roman-to-integer", title: "Roman to Integer", platform: "leetcode", url: "https://leetcode.com/problems/roman-to-integer/", difficulty: "easy", topic: "Math", pattern: "mixed-recognition", estMinutes: 12, hint: "Add each value; subtract when a smaller precedes a larger.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-rotate-image", title: "Rotate Image", platform: "leetcode", url: "https://leetcode.com/problems/rotate-image/", difficulty: "medium", topic: "Math", pattern: "mixed-recognition", estMinutes: 20, hint: "Transpose the matrix, then reverse each row.", companyTags: ["Amazon", "Microsoft", "Apple"], freshness: "2026-07-01" },
  { id: "lc-spiral-matrix", title: "Spiral Matrix", platform: "leetcode", url: "https://leetcode.com/problems/spiral-matrix/", difficulty: "medium", topic: "Math", pattern: "mixed-recognition", estMinutes: 22, hint: "Peel layers: right, down, left, up, shrinking bounds.", companyTags: ["Amazon", "Microsoft", "Google"], freshness: "2026-07-01" },
  { id: "lc-set-matrix-zeroes", title: "Set Matrix Zeroes", platform: "leetcode", url: "https://leetcode.com/problems/set-matrix-zeroes/", difficulty: "medium", topic: "Math", pattern: "mixed-recognition", estMinutes: 22, hint: "Use the first row/column as flags to mark zero rows/cols.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-powx-n", title: "Pow(x, n)", platform: "leetcode", url: "https://leetcode.com/problems/powx-n/", difficulty: "medium", topic: "Math", pattern: "mixed-recognition", estMinutes: 20, hint: "Fast exponentiation by squaring; handle negative n.", companyTags: ["Meta", "Google"], freshness: "2026-07-01" },
];
