import type { PracticeItem } from "@/lib/schema";
import { LEETCODE_75 } from "./practice-lc75";
import { PATTERN_BANK } from "./pattern-bank";

/**
 * Curated external practice. We store only canonical URLs + metadata and a
 * spoiler-free hint — never the copyrighted problem statement (PRD FR-011,
 * GH-014). Company tags are community-curated and informational.
 */
const BASE_ITEMS: PracticeItem[] = [
  {
    id: "lc-two-sum",
    title: "Two Sum",
    platform: "leetcode",
    url: "https://leetcode.com/problems/two-sum/",
    difficulty: "easy",
    topic: "Arrays",
    pattern: "frequency-hashing",
    estMinutes: 15,
    hint: "A hash map lets you check for the complement in one pass.",
    companyTags: ["Amazon", "Google", "Microsoft"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-best-time-stock",
    title: "Best Time to Buy and Sell Stock",
    platform: "leetcode",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    difficulty: "easy",
    topic: "Arrays",
    pattern: "sliding-window",
    estMinutes: 15,
    hint: "Track the minimum price seen so far while scanning left to right.",
    companyTags: ["Amazon", "Meta"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-contains-duplicate",
    title: "Contains Duplicate",
    platform: "leetcode",
    url: "https://leetcode.com/problems/contains-duplicate/",
    difficulty: "easy",
    topic: "Arrays",
    pattern: "frequency-hashing",
    estMinutes: 10,
    hint: "A set answers 'have I seen this before?' in O(1) average time.",
    companyTags: ["Amazon", "Google"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-valid-anagram",
    title: "Valid Anagram",
    platform: "leetcode",
    url: "https://leetcode.com/problems/valid-anagram/",
    difficulty: "easy",
    topic: "Strings",
    pattern: "frequency-hashing",
    estMinutes: 12,
    hint: "Compare character counts, not sorted strings, for O(n).",
    companyTags: ["Amazon", "Bloomberg"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-product-except-self",
    title: "Product of Array Except Self",
    platform: "leetcode",
    url: "https://leetcode.com/problems/product-of-array-except-self/",
    difficulty: "medium",
    topic: "Arrays",
    pattern: "prefix-sums",
    estMinutes: 20,
    hint: "Combine a prefix product and a suffix product — no division needed.",
    companyTags: ["Meta", "Amazon", "Microsoft"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-maximum-subarray",
    title: "Maximum Subarray",
    platform: "leetcode",
    url: "https://leetcode.com/problems/maximum-subarray/",
    difficulty: "medium",
    topic: "Arrays",
    pattern: "one-d-dp",
    estMinutes: 20,
    hint: "Kadane's idea: extend or restart the running sum at each index.",
    companyTags: ["Amazon", "Microsoft", "LinkedIn"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-binary-search",
    title: "Binary Search",
    platform: "leetcode",
    url: "https://leetcode.com/problems/binary-search/",
    difficulty: "easy",
    topic: "Binary Search",
    pattern: "binary-search-answer",
    estMinutes: 12,
    hint: "Keep a half-open invariant and always shrink the search space.",
    companyTags: ["Google", "Amazon"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-search-rotated",
    title: "Search in Rotated Sorted Array",
    platform: "leetcode",
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    difficulty: "medium",
    topic: "Binary Search",
    pattern: "binary-search-answer",
    estMinutes: 25,
    hint: "One side of mid is always sorted — decide which half to keep.",
    companyTags: ["Meta", "Amazon", "Microsoft"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-koko-bananas",
    title: "Koko Eating Bananas",
    platform: "leetcode",
    url: "https://leetcode.com/problems/koko-eating-bananas/",
    difficulty: "medium",
    topic: "Binary Search",
    pattern: "binary-search-answer",
    estMinutes: 25,
    hint: "Binary search on the eating speed, not the array indices.",
    companyTags: ["Google", "Meta"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-valid-parentheses",
    title: "Valid Parentheses",
    platform: "leetcode",
    url: "https://leetcode.com/problems/valid-parentheses/",
    difficulty: "easy",
    topic: "Stacks",
    pattern: "monotonic-stack",
    estMinutes: 15,
    hint: "Push openers; on a closer, the top must be its match.",
    companyTags: ["Amazon", "Google", "Microsoft"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-min-stack",
    title: "Min Stack",
    platform: "leetcode",
    url: "https://leetcode.com/problems/min-stack/",
    difficulty: "medium",
    topic: "Stacks",
    pattern: "monotonic-stack",
    estMinutes: 20,
    hint: "Store the running minimum alongside each pushed value.",
    companyTags: ["Amazon", "Bloomberg"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-reverse-linked-list",
    title: "Reverse Linked List",
    platform: "leetcode",
    url: "https://leetcode.com/problems/reverse-linked-list/",
    difficulty: "easy",
    topic: "Linked Lists",
    pattern: "fast-slow-pointers",
    estMinutes: 15,
    hint: "Walk the list re-pointing each node's next to its predecessor.",
    companyTags: ["Amazon", "Microsoft", "Meta"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-linked-list-cycle",
    title: "Linked List Cycle",
    platform: "leetcode",
    url: "https://leetcode.com/problems/linked-list-cycle/",
    difficulty: "easy",
    topic: "Linked Lists",
    pattern: "fast-slow-pointers",
    estMinutes: 15,
    hint: "Two runners at different speeds meet inside a cycle.",
    companyTags: ["Amazon", "Microsoft"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-merge-two-lists",
    title: "Merge Two Sorted Lists",
    platform: "leetcode",
    url: "https://leetcode.com/problems/merge-two-sorted-lists/",
    difficulty: "easy",
    topic: "Linked Lists",
    pattern: "two-pointers",
    estMinutes: 15,
    hint: "A dummy head simplifies stitching the smaller node each step.",
    companyTags: ["Amazon", "Apple"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-longest-substring",
    title: "Longest Substring Without Repeating Characters",
    platform: "leetcode",
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    difficulty: "medium",
    topic: "Strings",
    pattern: "sliding-window",
    estMinutes: 25,
    hint: "Grow a window; shrink from the left when a repeat enters.",
    companyTags: ["Amazon", "Google", "Meta"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-valid-palindrome",
    title: "Valid Palindrome",
    platform: "leetcode",
    url: "https://leetcode.com/problems/valid-palindrome/",
    difficulty: "easy",
    topic: "Strings",
    pattern: "two-pointers",
    estMinutes: 12,
    hint: "Converge two pointers from both ends, skipping non-alphanumerics.",
    companyTags: ["Meta", "Microsoft"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-3sum",
    title: "3Sum",
    platform: "leetcode",
    url: "https://leetcode.com/problems/3sum/",
    difficulty: "medium",
    topic: "Arrays",
    pattern: "two-pointers",
    estMinutes: 30,
    hint: "Sort, fix one number, then two-pointer the rest; skip duplicates.",
    companyTags: ["Amazon", "Meta", "Google"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-number-of-islands",
    title: "Number of Islands",
    platform: "leetcode",
    url: "https://leetcode.com/problems/number-of-islands/",
    difficulty: "medium",
    topic: "Graphs",
    pattern: "graph-traversal",
    estMinutes: 25,
    hint: "Flood-fill each unvisited land cell; count how many fills you start.",
    companyTags: ["Amazon", "Google", "Microsoft"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-climbing-stairs",
    title: "Climbing Stairs",
    platform: "leetcode",
    url: "https://leetcode.com/problems/climbing-stairs/",
    difficulty: "easy",
    topic: "Dynamic Programming",
    pattern: "one-d-dp",
    estMinutes: 15,
    hint: "Ways to reach step n = ways to n-1 plus ways to n-2 (Fibonacci).",
    companyTags: ["Amazon", "Adobe"],
    freshness: "2026-06-01",
  },
  {
    id: "lc-coin-change",
    title: "Coin Change",
    platform: "leetcode",
    url: "https://leetcode.com/problems/coin-change/",
    difficulty: "medium",
    topic: "Dynamic Programming",
    pattern: "one-d-dp",
    estMinutes: 30,
    hint: "Best for amount a = 1 + min over coins of best(a - coin).",
    companyTags: ["Amazon", "Google"],
    freshness: "2026-06-01",
  },
  {
    id: "cf-watermelon",
    title: "Watermelon",
    platform: "codeforces",
    url: "https://codeforces.com/problemset/problem/4/A",
    difficulty: "intro",
    topic: "Math",
    estMinutes: 10,
    hint: "Any even number ≥ 4 splits into two positive even parts.",
    companyTags: ["Codeforces"],
    freshness: "2026-06-01",
  },
  {
    id: "cf-theatre-square",
    title: "Theatre Square",
    platform: "codeforces",
    url: "https://codeforces.com/problemset/problem/1/A",
    difficulty: "easy",
    topic: "Math",
    estMinutes: 12,
    hint: "Ceil-divide each dimension by the flagstone size, then multiply.",
    companyTags: ["Codeforces"],
    freshness: "2026-06-01",
  },
  {
    id: "cf-way-too-long-words",
    title: "Way Too Long Words",
    platform: "codeforces",
    url: "https://codeforces.com/problemset/problem/71/A",
    difficulty: "easy",
    topic: "Strings",
    estMinutes: 12,
    hint: "Abbreviate words longer than 10 as first + count + last.",
    companyTags: ["Codeforces"],
    freshness: "2026-06-01",
  },
];

function dedupById(items: PracticeItem[]): PracticeItem[] {
  const seen = new Set<string>();
  const out: PracticeItem[] = [];
  for (const it of items) {
    if (!seen.has(it.id)) {
      seen.add(it.id);
      out.push(it);
    }
  }
  return out;
}

/** Full deduplicated catalog: base + LeetCode 75 + the comprehensive pattern bank. */
export const PRACTICE_ITEMS: PracticeItem[] = dedupById([
  ...BASE_ITEMS,
  ...LEETCODE_75,
  ...PATTERN_BANK,
]);

export function getPracticeItem(id: string) {
  return PRACTICE_ITEMS.find((p) => p.id === id);
}

export const ALL_COMPANY_TAGS = Array.from(
  new Set(PRACTICE_ITEMS.flatMap((p) => p.companyTags))
).sort();

export const ALL_PRACTICE_TOPICS = Array.from(
  new Set(PRACTICE_ITEMS.map((p) => p.topic))
).sort();
