import type { PracticeItem } from "@/lib/schema";

/**
 * Pattern-focused practice set (LeetCode 75 / Blind-style). Each problem is
 * tagged with the pattern it reinforces so the Pattern Lab ladders stay full.
 * We store only canonical URLs + metadata — never the problem statement.
 */
export const LEETCODE_75: PracticeItem[] = [
  // ---- Hashing / frequency ----
  { id: "lc-group-anagrams", title: "Group Anagrams", platform: "leetcode", url: "https://leetcode.com/problems/group-anagrams/", difficulty: "medium", topic: "Hashing", pattern: "frequency-hashing", estMinutes: 20, hint: "Group by a sorted-letter signature used as the map key.", companyTags: ["Amazon", "Meta", "Uber"], freshness: "2026-07-01" },
  { id: "lc-top-k-frequent", title: "Top K Frequent Elements", platform: "leetcode", url: "https://leetcode.com/problems/top-k-frequent-elements/", difficulty: "medium", topic: "Hashing", pattern: "top-k-heap", estMinutes: 20, hint: "Count frequencies, then bucket-sort or use a size-k heap.", companyTags: ["Amazon", "Meta", "Google"], freshness: "2026-07-01" },
  { id: "lc-subarray-sum-k", title: "Subarray Sum Equals K", platform: "leetcode", url: "https://leetcode.com/problems/subarray-sum-equals-k/", difficulty: "medium", topic: "Arrays", pattern: "prefix-sums", estMinutes: 25, hint: "Store prefix-sum counts; look for prefix − k in the map.", companyTags: ["Meta", "Amazon"], freshness: "2026-07-01" },

  // ---- Two pointers ----
  { id: "lc-two-sum-ii", title: "Two Sum II — Input Array Is Sorted", platform: "leetcode", url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/", difficulty: "medium", topic: "Arrays", pattern: "two-pointers", estMinutes: 15, hint: "Converge two pointers from both ends by comparing the sum.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-container-water", title: "Container With Most Water", platform: "leetcode", url: "https://leetcode.com/problems/container-with-most-water/", difficulty: "medium", topic: "Arrays", pattern: "two-pointers", estMinutes: 20, hint: "Move the shorter wall inward — it's the limiting side.", companyTags: ["Amazon", "Meta", "Google"], freshness: "2026-07-01" },

  // ---- Sliding window ----
  { id: "lc-min-window-substring", title: "Minimum Window Substring", platform: "leetcode", url: "https://leetcode.com/problems/minimum-window-substring/", difficulty: "hard", topic: "Strings", pattern: "sliding-window", estMinutes: 35, hint: "Expand to cover all needed chars, then shrink to the minimum.", companyTags: ["Amazon", "Meta", "Google"], freshness: "2026-07-01" },
  { id: "lc-longest-repeating", title: "Longest Repeating Character Replacement", platform: "leetcode", url: "https://leetcode.com/problems/longest-repeating-character-replacement/", difficulty: "medium", topic: "Strings", pattern: "sliding-window", estMinutes: 25, hint: "Window is valid while (len − maxFreq) ≤ k.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-find-anagrams", title: "Find All Anagrams in a String", platform: "leetcode", url: "https://leetcode.com/problems/find-all-anagrams-in-a-string/", difficulty: "medium", topic: "Strings", pattern: "sliding-window", estMinutes: 25, hint: "Slide a fixed-size window and compare frequency counts.", companyTags: ["Amazon", "Uber"], freshness: "2026-07-01" },
  { id: "lc-permutation-in-string", title: "Permutation in String", platform: "leetcode", url: "https://leetcode.com/problems/permutation-in-string/", difficulty: "medium", topic: "Strings", pattern: "sliding-window", estMinutes: 22, hint: "Fixed-size window whose char counts match the target.", companyTags: ["Microsoft", "Amazon"], freshness: "2026-07-01" },

  // ---- Fast & slow pointers ----
  { id: "lc-middle-linked-list", title: "Middle of the Linked List", platform: "leetcode", url: "https://leetcode.com/problems/middle-of-the-linked-list/", difficulty: "easy", topic: "Linked Lists", pattern: "fast-slow-pointers", estMinutes: 12, hint: "When fast reaches the end, slow sits at the middle.", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-happy-number", title: "Happy Number", platform: "leetcode", url: "https://leetcode.com/problems/happy-number/", difficulty: "easy", topic: "Math", pattern: "fast-slow-pointers", estMinutes: 18, hint: "Cycle detection on the digit-square sequence.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },

  // ---- Binary search ----
  { id: "lc-find-min-rotated", title: "Find Minimum in Rotated Sorted Array", platform: "leetcode", url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", difficulty: "medium", topic: "Binary Search", pattern: "binary-search-answer", estMinutes: 20, hint: "Compare mid to the right end to pick the unsorted half.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-time-based-store", title: "Time Based Key-Value Store", platform: "leetcode", url: "https://leetcode.com/problems/time-based-key-value-store/", difficulty: "medium", topic: "Binary Search", pattern: "binary-search-answer", estMinutes: 25, hint: "Binary search timestamps stored in sorted order per key.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },

  // ---- Merge intervals ----
  { id: "lc-merge-intervals", title: "Merge Intervals", platform: "leetcode", url: "https://leetcode.com/problems/merge-intervals/", difficulty: "medium", topic: "Intervals", pattern: "merge-intervals", estMinutes: 22, hint: "Sort by start, then extend or push each interval.", companyTags: ["Amazon", "Meta", "Google"], freshness: "2026-07-01" },
  { id: "lc-insert-interval", title: "Insert Interval", platform: "leetcode", url: "https://leetcode.com/problems/insert-interval/", difficulty: "medium", topic: "Intervals", pattern: "merge-intervals", estMinutes: 22, hint: "Add all before, merge overlaps, add all after.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-non-overlapping", title: "Non-overlapping Intervals", platform: "leetcode", url: "https://leetcode.com/problems/non-overlapping-intervals/", difficulty: "medium", topic: "Intervals", pattern: "greedy-choice", estMinutes: 22, hint: "Sort by end; greedily keep the earliest-finishing intervals.", companyTags: ["Amazon"], freshness: "2026-07-01" },

  // ---- Monotonic stack ----
  { id: "lc-daily-temperatures", title: "Daily Temperatures", platform: "leetcode", url: "https://leetcode.com/problems/daily-temperatures/", difficulty: "medium", topic: "Stacks", pattern: "monotonic-stack", estMinutes: 20, hint: "Keep a stack of indices with decreasing temperatures.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-largest-rectangle", title: "Largest Rectangle in Histogram", platform: "leetcode", url: "https://leetcode.com/problems/largest-rectangle-in-histogram/", difficulty: "hard", topic: "Stacks", pattern: "monotonic-stack", estMinutes: 35, hint: "Monotonic increasing stack; pop to settle each bar's width.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },

  // ---- Heap / top-k ----
  { id: "lc-kth-largest", title: "Kth Largest Element in an Array", platform: "leetcode", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/", difficulty: "medium", topic: "Heaps", pattern: "top-k-heap", estMinutes: 20, hint: "A size-k min-heap, or quickselect for O(n) average.", companyTags: ["Amazon", "Meta", "Google"], freshness: "2026-07-01" },
  { id: "lc-k-closest-points", title: "K Closest Points to Origin", platform: "leetcode", url: "https://leetcode.com/problems/k-closest-points-to-origin/", difficulty: "medium", topic: "Heaps", pattern: "top-k-heap", estMinutes: 20, hint: "Max-heap of size k on squared distance.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-task-scheduler", title: "Task Scheduler", platform: "leetcode", url: "https://leetcode.com/problems/task-scheduler/", difficulty: "medium", topic: "Heaps", pattern: "greedy-choice", estMinutes: 28, hint: "Schedule the most frequent task first each cycle.", companyTags: ["Meta", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-find-median-stream", title: "Find Median from Data Stream", platform: "leetcode", url: "https://leetcode.com/problems/find-median-from-data-stream/", difficulty: "hard", topic: "Heaps", pattern: "top-k-heap", estMinutes: 30, hint: "Balance a max-heap (low half) against a min-heap (high half).", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },

  // ---- Trees ----
  { id: "lc-invert-binary-tree", title: "Invert Binary Tree", platform: "leetcode", url: "https://leetcode.com/problems/invert-binary-tree/", difficulty: "easy", topic: "Trees", pattern: "tree-traversal", estMinutes: 12, hint: "Swap children, then recurse into both.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-max-depth-binary-tree", title: "Maximum Depth of Binary Tree", platform: "leetcode", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", difficulty: "easy", topic: "Trees", pattern: "tree-traversal", estMinutes: 10, hint: "1 + max(depth(left), depth(right)).", companyTags: ["Amazon"], freshness: "2026-07-01" },
  { id: "lc-diameter-binary-tree", title: "Diameter of Binary Tree", platform: "leetcode", url: "https://leetcode.com/problems/diameter-of-binary-tree/", difficulty: "easy", topic: "Trees", pattern: "tree-traversal", estMinutes: 18, hint: "Longest path = max over nodes of leftHeight + rightHeight.", companyTags: ["Meta", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-lca-bst", title: "Lowest Common Ancestor of a BST", platform: "leetcode", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", difficulty: "medium", topic: "Trees", pattern: "tree-traversal", estMinutes: 15, hint: "Walk down; the split point where p and q diverge is the LCA.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-level-order", title: "Binary Tree Level Order Traversal", platform: "leetcode", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", difficulty: "medium", topic: "Trees", pattern: "graph-traversal", estMinutes: 18, hint: "BFS with a queue, capturing one level per round.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },

  // ---- Graphs ----
  { id: "lc-clone-graph", title: "Clone Graph", platform: "leetcode", url: "https://leetcode.com/problems/clone-graph/", difficulty: "medium", topic: "Graphs", pattern: "graph-traversal", estMinutes: 25, hint: "DFS/BFS with a map from original node to its copy.", companyTags: ["Meta", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-course-schedule", title: "Course Schedule", platform: "leetcode", url: "https://leetcode.com/problems/course-schedule/", difficulty: "medium", topic: "Graphs", pattern: "topological-sort", estMinutes: 28, hint: "Detect a cycle via topological sort (Kahn's or DFS colors).", companyTags: ["Amazon", "Google", "Meta"], freshness: "2026-07-01" },
  { id: "lc-pacific-atlantic", title: "Pacific Atlantic Water Flow", platform: "leetcode", url: "https://leetcode.com/problems/pacific-atlantic-water-flow/", difficulty: "medium", topic: "Graphs", pattern: "graph-traversal", estMinutes: 30, hint: "Flood inward from each ocean; answer is the intersection.", companyTags: ["Google", "Amazon"], freshness: "2026-07-01" },
  { id: "lc-rotting-oranges", title: "Rotting Oranges", platform: "leetcode", url: "https://leetcode.com/problems/rotting-oranges/", difficulty: "medium", topic: "Graphs", pattern: "graph-traversal", estMinutes: 25, hint: "Multi-source BFS from all rotten oranges at once.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-number-of-provinces", title: "Number of Provinces", platform: "leetcode", url: "https://leetcode.com/problems/number-of-provinces/", difficulty: "medium", topic: "Graphs", pattern: "union-find", estMinutes: 20, hint: "Count connected components with DFS or union-find.", companyTags: ["Amazon"], freshness: "2026-07-01" },

  // ---- Backtracking ----
  { id: "lc-subsets", title: "Subsets", platform: "leetcode", url: "https://leetcode.com/problems/subsets/", difficulty: "medium", topic: "Backtracking", pattern: "backtracking", estMinutes: 20, hint: "At each index, branch on include vs. exclude.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-permutations", title: "Permutations", platform: "leetcode", url: "https://leetcode.com/problems/permutations/", difficulty: "medium", topic: "Backtracking", pattern: "backtracking", estMinutes: 22, hint: "Swap-in each unused element, recurse, swap back.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-combination-sum", title: "Combination Sum", platform: "leetcode", url: "https://leetcode.com/problems/combination-sum/", difficulty: "medium", topic: "Backtracking", pattern: "backtracking", estMinutes: 25, hint: "Recurse allowing reuse; prune when the remainder goes negative.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-word-search", title: "Word Search", platform: "leetcode", url: "https://leetcode.com/problems/word-search/", difficulty: "medium", topic: "Backtracking", pattern: "backtracking", estMinutes: 30, hint: "DFS from each cell, marking visited and undoing on return.", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },

  // ---- Greedy ----
  { id: "lc-jump-game", title: "Jump Game", platform: "leetcode", url: "https://leetcode.com/problems/jump-game/", difficulty: "medium", topic: "Greedy", pattern: "greedy-choice", estMinutes: 18, hint: "Track the farthest index reachable so far.", companyTags: ["Amazon", "Meta"], freshness: "2026-07-01" },
  { id: "lc-gas-station", title: "Gas Station", platform: "leetcode", url: "https://leetcode.com/problems/gas-station/", difficulty: "medium", topic: "Greedy", pattern: "greedy-choice", estMinutes: 22, hint: "If total gas ≥ cost, the unique start is just after the lowest tank.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-hand-of-straights", title: "Hand of Straights", platform: "leetcode", url: "https://leetcode.com/problems/hand-of-straights/", difficulty: "medium", topic: "Greedy", pattern: "greedy-choice", estMinutes: 22, hint: "Always start a group from the smallest remaining card.", companyTags: ["Google"], freshness: "2026-07-01" },

  // ---- Dynamic programming ----
  { id: "lc-house-robber", title: "House Robber", platform: "leetcode", url: "https://leetcode.com/problems/house-robber/", difficulty: "medium", topic: "Dynamic Programming", pattern: "one-d-dp", estMinutes: 18, hint: "dp[i] = max(dp[i-1], dp[i-2] + nums[i]).", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-longest-increasing-subsequence", title: "Longest Increasing Subsequence", platform: "leetcode", url: "https://leetcode.com/problems/longest-increasing-subsequence/", difficulty: "medium", topic: "Dynamic Programming", pattern: "one-d-dp", estMinutes: 28, hint: "O(n²) DP, or patience sorting with binary search for O(n log n).", companyTags: ["Amazon", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-unique-paths", title: "Unique Paths", platform: "leetcode", url: "https://leetcode.com/problems/unique-paths/", difficulty: "medium", topic: "Dynamic Programming", pattern: "grid-dp", estMinutes: 18, hint: "dp[r][c] = dp[r-1][c] + dp[r][c-1].", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-longest-common-subsequence", title: "Longest Common Subsequence", platform: "leetcode", url: "https://leetcode.com/problems/longest-common-subsequence/", difficulty: "medium", topic: "Dynamic Programming", pattern: "grid-dp", estMinutes: 25, hint: "2-D table over prefixes of both strings.", companyTags: ["Amazon", "Google"], freshness: "2026-07-01" },
  { id: "lc-word-break", title: "Word Break", platform: "leetcode", url: "https://leetcode.com/problems/word-break/", difficulty: "medium", topic: "Dynamic Programming", pattern: "one-d-dp", estMinutes: 25, hint: "dp[i] true if some split point j gives dp[j] and dict has s[j..i).", companyTags: ["Amazon", "Meta", "Google"], freshness: "2026-07-01" },

  // ---- Advanced structures ----
  { id: "lc-implement-trie", title: "Implement Trie (Prefix Tree)", platform: "leetcode", url: "https://leetcode.com/problems/implement-trie-prefix-tree/", difficulty: "medium", topic: "Tries", pattern: "backtracking", estMinutes: 25, hint: "Each node holds child links and an end-of-word flag.", companyTags: ["Amazon", "Google", "Microsoft"], freshness: "2026-07-01" },
  { id: "lc-range-sum-query", title: "Range Sum Query — Mutable", platform: "leetcode", url: "https://leetcode.com/problems/range-sum-query-mutable/", difficulty: "medium", topic: "Advanced", pattern: "prefix-sums", estMinutes: 30, hint: "A Fenwick tree (BIT) gives O(log n) updates and prefix sums.", companyTags: ["Google"], freshness: "2026-07-01" },
];
